### ISSUE TITLE
drake can handle non-R dependencies

### ISSUE THREAD

**Issue by wlandau** [aaronpeikert/reproducible-research#7]
In the [Related approaches](https://github.com/aaronpeikert/reproducible-research/blob/25333f2d646f4ea2510deebeb0dd732f00506da7/manuscript.Rmd#L371) section, I see a comment about `drake`:

> The drake package is directly inspired by Make but can only handle dependencies within R.

Did you mean to claim that the only admissible dependencies are R objects? R object targets are certainly the easiest to deal with in `drake`, but you can also declare files, directories, R Markdown reports, and even URLs as dependencies. When you create your `drake` plan (`drake`'s version of a Makefile) you can declare file dependencies with three different keywords:

1. `file_in()`: input files, directories, and/or URLs for a given target. A change to these files will invalidate the target that accepts them.
2. `file_out()`: files and directories produced by a target. If a `file_out()` file gets corrupted, `drake::make()` will rebuild the target that produced it. `file_out()` files for one target can be `file_in()` files for targets downstream, and `drake` understands dependency relationships induced by `file_in()`/`file_out()` relationships.
3. `knitr_in()`: an input R Markdown / `knitr` source file that uses `drake` targets. R Markdown reports can depend on `drake` targets, and you can render them inside or outside the pipeline.

Here is an example using all three keywords. The graph below shows how `drake` respects dependency relationships that depend on files. The relationships are detected with static code analysis, which powers the domain-specific language implemented in `drake_plan()`.

```` r
library(drake)
library(rmarkdown)
library(tidyverse)
library(webshot)

# Say you start out with a data file
write_csv(mtcars, "mtcars.csv")

# Let's use a report that depends on a drake target.
lines <- c(
  "---",
  "title: \"R Markdown report with drake targets inside\"",
  "output: html_document",
  "---",
  "",
  "In reports, the loadd() and readd() functions serve 2 purposes: ",
  "they tell drake that the report depends on certain targets, ",
  "and they load drake targets from the cache when it comes time ",
  "to run the report.",
  "",
  "```{r}",
  "library(drake)",
  "readd(plot)",
  "```"
)
writeLines(lines, "report.Rmd")

# The plan is like a Makefile.
plan <- drake_plan(
  data = read_csv(file_in("mtcars.csv"), col_types = cols()),
  munge_step = write_csv(
    select(data, -cyl),
    file_out("mtcars_munged.csv")
  ),
  plot = {
    data <- read_csv(file_in("mtcars_munged.csv"), col_types = cols())
    ggplot(data) + geom_point(aes(x = wt, y = mpg))
  },
  report = render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.html"),
    quiet = TRUE
  )
)

# Here is what the workflow looks like.
# drake understands dependency relationships that
# mix files and targets.
# The graph comes out better as an interactive HTML widget.
vis_drake_graph(plan)
````

![](https://i.imgur.com/Om0HZOq.png)

``` r

# Now let's run the work.
make(plan)
#> target data
#> target munge_step
#> target plot
#> target report

# What does our report look like?
webshot("report.html")
```

![](https://i.imgur.com/dGT6pVc.png)

``` r

# Everything is up to date now.
make(plan)
#> All targets are already up to date.

# But if we corrupt or change a file, the some targets need
# to rebuild. If the file's hash is the same as before,
# drake is smart enough to know it can stop building downstream
# targets in this workflow.
write_csv(iris, "mtcars_munged.csv")

make(plan)
#> target munge_step
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Full disclosure: I am the creator and maintainer of `drake`.

**Comment by aaronpeikert** [comment]
Sorry I meant to claim that `drake` is focused on R objects as targets, but thank you for pointing out that the sentence does not convey this! However, as I see now, not even that is true anymore.
It is over one and a half year ago that I used `drake` for a project and `drake` came a long way since then, just awe-inspiring. Then `drake` seemed to be extremely R-centric (which has its merits), or that is at least how I remember it. Now the `file_in()` / `file_out()` mechanisms seems more flexible.
We will revise the sentence. Keep up the great work with `drake`!

Offtopic: I would love to see tighter integration between `drake` and  `docker`, maybe there is some way to declare the docker image as a dependency and provide facilities to rebuild the image on change of the Dockerfile automatically triggering all other targets. That would be plain awesome!

**Comment by wlandau** [comment]
Thanks for the encouragement and for agreeing to revise the claim!

I do not often use Docker myself, but maybe `file_in()` and friends could track both Dockerfile and the image file if the image is part of the pipeline. Alternatively, some folks are actually running `drake` within Docker, and @noamross has a nice example at <https://gitlab.com/ecohealthalliance/drake-gitlab-docker-example>.

**Comment by noamross** [comment]
> maybe there is some way to declare the docker image as a dependency and provide facilities to rebuild the image on change of the Dockerfile automatically triggering all other targets

This might be possible now using a docker client like `stevedore` and custom `drake` triggers, but as in my example, I tend to think of drake as nested _within_ Docker and/or other build environments like (`renv`), which are better designed for handling software dependencies.

**Comment by aaronpeikert** [comment]
@noamross Thank you for this outline how it may be possible. I see where you are coming from with the division of tasks between software dependency management and file dependency management where the latter is operating within the former. However, it is not entirely satisfactory for me to not assume targets to be outdated if the software is updated. Since Dockerfiles track changes of the environment concisely and in one place, there should be an organic way to combine both.
